### ISSUE TITLE
Issue with kivy.version.__version__ in app.py

### ISSUE THREAD

**Issue by Melan2001** [Cheaterman/panda3d-kivy#18]
After upgrading to 0.2.1(latest version as of 10/31):

I got:

Traceback (most recent call last):
```
   File "...\Panda3D-1.10.7-x64\python\lib\site-packages\panda3d_kivy\app.py", line 44, in init_window
     self.run()  # root shouldn't be set before run() is called
   File "...\Panda3D-1.10.7-x64\python\lib\site-packages\panda3d_kivy\app.py", line 64, in run
     version, *_ = kivy.parse_kivy_version(kivy.version.__version__)
AttributeError: 'str' object has no attribute '__version__'
```

Seems that kivy.version returns a string.

Thanks!

**Comment by Cheaterman** [comment]
Thanks for the report! Still wondering why it wouldn't work for you on Kivy 1.11.1 while it did for me, but it doesn't really matter now - we even fixed 2.x compatibility. :-)

**Comment by Melan2001** [comment]
Thanks. Tested with the new version: works perfectly.
